# -*- coding: utf-8 -*-
"""NASA turbofan jet engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foNjRJPsMny6gYOHvw4EKwN7TRQN3Ye-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# ================================
# 2. LOAD DATA
# ================================
cols = ['unit', 'cycle'] + \
       [f'op_setting_{i}' for i in range(1,4)] + \
       [f'sensor_{i}' for i in range(1,22)]

train = pd.read_csv("/content/sample_data/train_FD001.txt", sep="\s+", header=None)
train.columns = cols

train.head()

# ================================
# 3. CREATE RUL (TARGET)
# ================================
max_cycle = train.groupby('unit')['cycle'].max().reset_index()
max_cycle.columns = ['unit', 'max_cycle']

train = train.merge(max_cycle, on='unit')

train['RUL'] = train['max_cycle'] - train['cycle']

train.columns

train.describe()

train.info()

# ================================
# 4. RUL CLIPPING
# ================================
train['RUL'] = train['RUL'].clip(upper=130)

"""Preprocessing"""

train.isnull().sum()

train.columns

train['max_cycle'].value_counts()

train

sns.histplot(train['RUL'])

train.skew().sort_values(ascending=False)

corr = train.corr()
sns.heatmap(corr)

train.nunique()

low_var_cols = [col for col in train.columns if train[col].nunique() <= 2]

train.drop(columns=low_var_cols, inplace=True)

train.columns

train['RUL'].value_counts()

sns.countplot(x='RUL', data=train)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=train)
plt.title('scatter Plot')
plt.show()

"""Modeling

"""

feature_cols = train.columns.difference(['unit', 'cycle', 'RUL'])

# ============================
# SPLIT BY UNIT (IMPORTANT)
#All units = [1,2,3,4,5] Train → [1,2,3] Val   → [4] Test  → [5]
#this will not create data lekage and no artifical high accuracy
# ============================
units = train['unit'].unique()

train_units = units[:int(len(units)*0.7)]
val_units = units[int(len(units)*0.7):int(len(units)*0.85)]
test_units = units[int(len(units)*0.85):]

train_df = train[train['unit'].isin(train_units)].copy()
val_df = train[train['unit'].isin(val_units)].copy()
test_df = train[train['unit'].isin(test_units)].copy()

# ============================
# SCALING
# ============================
scaler = MinMaxScaler()

train_df[feature_cols] = scaler.fit_transform(train_df[feature_cols])
val_df[feature_cols] = scaler.transform(val_df[feature_cols])
test_df[feature_cols] = scaler.transform(test_df[feature_cols])

# ============================
# SEQUENCE CREATION
# ============================
def create_sequences(df, seq_length, feature_cols):
    X, y = [], []

    for unit in df['unit'].unique():
        unit_data = df[df['unit'] == unit]

        for i in range(len(unit_data) - seq_length):
            seq = unit_data[feature_cols].iloc[i:i+seq_length].values
            label = unit_data['RUL'].iloc[i+seq_length]

            X.append(seq)
            y.append(label)

    return np.array(X), np.array(y)

SEQ_LENGTH = 30

X_train, y_train = create_sequences(train_df, SEQ_LENGTH, feature_cols)
X_val, y_val = create_sequences(val_df, SEQ_LENGTH, feature_cols)
X_test, y_test = create_sequences(test_df, SEQ_LENGTH, feature_cols)

print("Train:", X_train.shape)
print("Val:", X_val.shape)
print("Test:", X_test.shape)

# ============================
# GRU MODEL
# ============================
model = Sequential()

model.add(GRU(64, return_sequences=True, input_shape=(SEQ_LENGTH, X_train.shape[2])))
model.add(Dropout(0.2))

model.add(GRU(32))
model.add(Dropout(0.2))

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model.summary()

# ============================
# TRAINING
# ============================
'''early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)'''

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=64,
    #callbacks=[early_stop]
)

# ============================
# EVALUATION
# ============================
y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("RMSE:", rmse)
print("MAE:", mae)

plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.legend()
plt.title("Loss Curve")
plt.show()

"""Fine tune"""

# ============================
# GRU MODEL (FINETUNED)
# ============================

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

model2 = Sequential()

# Layer 1
model2.add(GRU(128, return_sequences=True, input_shape=(SEQ_LENGTH, X_train.shape[2])))
model2.add(Dropout(0.3))

# Layer 2
model2.add(GRU(64, return_sequences=True))
model2.add(Dropout(0.3))

# Layer 3
model2.add(GRU(32))
model2.add(Dropout(0.2))

# Output layer
model2.add(Dense(1))

# ============================
# COMPILE
# ============================

#optimizer = Adam(learning_rate=0.0005)

model2.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model2.summary()

# ============================
# CALLBACKS
# ============================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=7,
    restore_best_weights=True
)

lr_scheduler = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    min_lr=1e-6
)

# ============================
# TRAINING
# ============================

history = model2.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,   # smaller batch → better learning
    callbacks=[early_stop, lr_scheduler],
    verbose=1
)

y_pred = model2.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("RMSE:", rmse)
print("MAE:", mae)

plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.legend()
plt.title("Loss Curve")
plt.show()

